#!/bin/bash
# Retrieve minor version number from (file) storage
MINOR=$(cat version/minor)
# Increment minor version number
let "MINOR++"
# Store incremented minor version number
echo $MINOR > version/minor

# Stage active changes and minor version number
git add active/* version/minor
# If given, user-defined message is used as git commit title
if [ "$1" != "" ]; then
	COMMSG=$1
	COMDESC="AUTO: Save #$MINOR"
else
	COMMSG="AUTO: Save #$MINOR"
	COMDESC=""
fi
# Commit active changes
git commit -m "$COMMSG" -m "$COMDESC"
