#!/bin/bash
MINOR=$(cat version/minor)
let "MINOR++"
echo $MINOR > version/minor
git add active/* version/minor
if [ "$1" != "" ]; then
	COMMSG=$1
	COMDESC="AUTO: Save #$MINOR"
else
	COMMSG="AUTO: Save #$MINOR"
	COMDESC=""
fi
git commit -m "$COMMSG" -m "$COMDESC"
