#!/bin/bash
cp --update --target-directory=stable active/*
MAJOR=$(cat "version/major")
let "MAJOR++"
echo $MAJOR > version/major
MINOR=$(cat "version/minor")
echo 0 > version/minor
git add stable/*
git commit -m "RELEASE: Version $MAJOR.$MINOR"
