#!/bin/bash
cp --update active/.* stable/ 
MAJOR=$(cat "version/major")
let "MAJOR++"
echo $MAJOR > version/major
MINOR=$(cat "version/minor")
echo 0 > version/minor
git add stable/* version/*
git commit -m "RELEASE: Version $MAJOR.$MINOR"
